version: "3"
services:
    app:
        image: golang:1.12.17
        volumes:
        - .:/app/
        working_dir: /app/
        command: go run main.go --port 8000 --skip-translation-fetch --config './data/config.json'
        ports:
            - "80:8000"
    prometheus:
        image: prom/prometheus:v2.18.1
        volumes:
            - ./data/prometheus/:/data/
        command:
            - "--config.file=/data/prometheus.yml"
        ports:
            - "9090:9090"
