version: "3"
services:
    app:
        image: golang:latest
        volumes:
        - .:/app/
        working_dir: /app/
        command: go run main.go --port 8000 --skip-translation-fetch --config './data/config.json'
        ports:
            - "80:8000"
        environment:
            # DBSTORAGE_DEBUG_SQL: 1
            # DBSTORAGE_DEBUG_VERBOSE: 1
