# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    working_directory: /go/src/github.com/nektro/mantle
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -v -u .
      - run: go test -v .
      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/
      - run: ./make_release.sh
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
